version: '3.7'
services:
  clouddesktop:
    container_name: clouddesktop
    image: cosi119/tb3-ros:v2
    network_mode: "host"
    environment:
      PASSWORD: dev@ros
      VNC_PASSWORD: dev@ros
    volumes:
      - type: bind
        source: /dev/shm
        target: /dev/shm
      - type: volume
        source: rospersistent
        target: /my_ros_data
        volume:
          nocopy: false
volumes:
  rospersistent:
    driver_opts:
      type: none
      device: ROSPERSISTENT-PATH
      o: bind
