version: '3.7'
services:
  clouddesktop:
    container_name: clouddesktop
    hostname: clouddesktop
    image: cosi119/tb3-ros:v2.1.0
    ports:
      - '80'
      - '6080'
      - '2222'
    environment:
      PASSWORD: dev@ros
      VNC_PASSWORD: dev@ros
      RESOLUTION: 1920x1080
    cap_add:
      - NET_ADMIN
    volumes:
      - type: bind
        source: /dev/shm
        target: /dev/shm
      - type: volume
        source: rospersistent
        target: /my_ros_data
        volume:
          nocopy: false
    healthcheck:
      disable: true
volumes:
  rospersistent:
    driver_opts:
      type: none
      device: ROSPERSISTENT-PATH
      o: bind
